/* ============================================================
   RÉINITIALISATION DES CATÉGORIES SODIV BUREAU
   Génère 15 catégories principales + sous + sous-sous
   ============================================================ */

SET XACT_ABORT ON;
BEGIN TRANSACTION;

-- 1) Catégorie temporaire pour préserver les produits existants
IF NOT EXISTS (SELECT 1 FROM Categories WHERE Nom = N'À reclasser')
BEGIN
    INSERT INTO Categories (Nom, Slug, IconeClass, EstActive, ParentId)
    VALUES (N'À reclasser', N'a-reclasser', N'fa-question-circle', 1, NULL);
END;

DECLARE @TempId INT = (SELECT Id FROM Categories WHERE Nom = N'À reclasser');

-- 2) Déplacer tous les produits vers la catégorie temporaire
UPDATE Produits SET CategorieId = @TempId WHERE CategorieId <> @TempId;

-- 3) Supprimer toutes les autres catégories
DELETE FROM Categories WHERE Id <> @TempId;

-- 4) Insertion des nouvelles catégories niveau par niveau

-- ════════ NIVEAU 0 (catégories principales) ════════
INSERT INTO Categories (Nom, Slug, IconeClass, EstActive, ParentId) VALUES
  (N'PAPETERIE', N'papeterie', N'fa-file-alt', 1, NULL),
  (N'CLASSEMENT & ARCHIVAGE', N'classement-archivage', N'fa-folder-open', 1, NULL),
  (N'ÉCRITURE & CORRECTION', N'ecriture-correction', N'fa-pen', 1, NULL),
  (N'PETITE FOURNITURE', N'petite-fourniture', N'fa-paperclip', 1, NULL),
  (N'ACCESSOIRES BUREAU & MACHINES', N'accessoires-bureau-machines', N'fa-briefcase', 1, NULL),
  (N'PRÉSENTATION & COMMUNICATION', N'presentation-communication', N'fa-chalkboard', 1, NULL),
  (N'INFORMATIQUE & ACCESSOIRES', N'informatique-accessoires', N'fa-laptop', 1, NULL),
  (N'IMPRIMANTES & CONSOMMABLES', N'imprimantes-consommables', N'fa-print', 1, NULL),
  (N'MOBILIER DE BUREAU', N'mobilier-de-bureau', N'fa-chair', 1, NULL),
  (N'SCOLAIRE & PARA-SCOLAIRE', N'scolaire-para-scolaire', N'fa-graduation-cap', 1, NULL),
  (N'SERVICES GÉNÉRAUX', N'services-generaux', N'fa-building', 1, NULL),
  (N'MOBILE & TÉLÉPHONIE', N'mobile-telephonie', N'fa-mobile-alt', 1, NULL),
  (N'PHOTO, AUDIO & VIDÉO', N'photo-audio-video', N'fa-camera', 1, NULL),
  (N'CADEAUX & PROMOTIONNEL', N'cadeaux-promotionnel', N'fa-gift', 1, NULL),
  (N'PROMOTIONS & BONNES AFFAIRES', N'promotions-bonnes-affaires', N'fa-fire', 1, NULL);

-- ════════ NIVEAU 1 (sous-catégories) ════════
INSERT INTO Categories (Nom, Slug, IconeClass, EstActive, ParentId) VALUES
  (N'Papiers Blancs & Ivoires', N'papeterie-papiers-blancs-ivoires', N'fa-file', 1, (SELECT Id FROM Categories WHERE Nom = N'PAPETERIE' AND ParentId IS NULL)),
  (N'Papiers Couleurs', N'papeterie-papiers-couleurs', N'fa-palette', 1, (SELECT Id FROM Categories WHERE Nom = N'PAPETERIE' AND ParentId IS NULL)),
  (N'Papiers Spéciaux', N'papeterie-papiers-speciaux', N'fa-star', 1, (SELECT Id FROM Categories WHERE Nom = N'PAPETERIE' AND ParentId IS NULL)),
  (N'Étiquettes & Papier Listing', N'papeterie-etiquettes-papier-listing', N'fa-tags', 1, (SELECT Id FROM Categories WHERE Nom = N'PAPETERIE' AND ParentId IS NULL)),
  (N'Courrier & Enveloppes', N'papeterie-courrier-enveloppes', N'fa-envelope', 1, (SELECT Id FROM Categories WHERE Nom = N'PAPETERIE' AND ParentId IS NULL)),
  (N'Travaux d''Impression', N'papeterie-travaux-d-impression', N'fa-print', 1, (SELECT Id FROM Categories WHERE Nom = N'PAPETERIE' AND ParentId IS NULL)),
  (N'Classeurs', N'classement-archivage-classeurs', N'fa-folder', 1, (SELECT Id FROM Categories WHERE Nom = N'CLASSEMENT & ARCHIVAGE' AND ParentId IS NULL)),
  (N'Intercalaires', N'classement-archivage-intercalaires', N'fa-list', 1, (SELECT Id FROM Categories WHERE Nom = N'CLASSEMENT & ARCHIVAGE' AND ParentId IS NULL)),
  (N'Archives & Boîtes', N'classement-archivage-archives-boites', N'fa-archive', 1, (SELECT Id FROM Categories WHERE Nom = N'CLASSEMENT & ARCHIVAGE' AND ParentId IS NULL)),
  (N'Trieur & Organisation', N'classement-archivage-trieur-organisation', N'fa-th-list', 1, (SELECT Id FROM Categories WHERE Nom = N'CLASSEMENT & ARCHIVAGE' AND ParentId IS NULL)),
  (N'Chemises & Sous-Chemises', N'classement-archivage-chemises-sous-chemises', N'fa-folder-minus', 1, (SELECT Id FROM Categories WHERE Nom = N'CLASSEMENT & ARCHIVAGE' AND ParentId IS NULL)),
  (N'Reliure & Spirales', N'classement-archivage-reliure-spirales', N'fa-book', 1, (SELECT Id FROM Categories WHERE Nom = N'CLASSEMENT & ARCHIVAGE' AND ParentId IS NULL)),
  (N'Stylos', N'ecriture-correction-stylos', N'fa-pen-fancy', 1, (SELECT Id FROM Categories WHERE Nom = N'ÉCRITURE & CORRECTION' AND ParentId IS NULL)),
  (N'Crayons', N'ecriture-correction-crayons', N'fa-pencil-alt', 1, (SELECT Id FROM Categories WHERE Nom = N'ÉCRITURE & CORRECTION' AND ParentId IS NULL)),
  (N'Marqueurs & Surligneurs', N'ecriture-correction-marqueurs-surligneurs', N'fa-marker', 1, (SELECT Id FROM Categories WHERE Nom = N'ÉCRITURE & CORRECTION' AND ParentId IS NULL)),
  (N'Correction', N'ecriture-correction-correction', N'fa-eraser', 1, (SELECT Id FROM Categories WHERE Nom = N'ÉCRITURE & CORRECTION' AND ParentId IS NULL)),
  (N'Agrafage', N'petite-fourniture-agrafage', N'fa-thumbtack', 1, (SELECT Id FROM Categories WHERE Nom = N'PETITE FOURNITURE' AND ParentId IS NULL)),
  (N'Perforation', N'petite-fourniture-perforation', N'fa-circle-notch', 1, (SELECT Id FROM Categories WHERE Nom = N'PETITE FOURNITURE' AND ParentId IS NULL)),
  (N'Attaches & Trombones', N'petite-fourniture-attaches-trombones', N'fa-link', 1, (SELECT Id FROM Categories WHERE Nom = N'PETITE FOURNITURE' AND ParentId IS NULL)),
  (N'Adhésifs & Colles', N'petite-fourniture-adhesifs-colles', N'fa-tape', 1, (SELECT Id FROM Categories WHERE Nom = N'PETITE FOURNITURE' AND ParentId IS NULL)),
  (N'Découpe & Mesure', N'petite-fourniture-decoupe-mesure', N'fa-cut', 1, (SELECT Id FROM Categories WHERE Nom = N'PETITE FOURNITURE' AND ParentId IS NULL)),
  (N'Rangement Bureau', N'accessoires-bureau-machines-rangement-bureau', N'fa-boxes', 1, (SELECT Id FROM Categories WHERE Nom = N'ACCESSOIRES BUREAU & MACHINES' AND ParentId IS NULL)),
  (N'Cahiers & Blocs', N'accessoires-bureau-machines-cahiers-blocs', N'fa-book-open', 1, (SELECT Id FROM Categories WHERE Nom = N'ACCESSOIRES BUREAU & MACHINES' AND ParentId IS NULL)),
  (N'Agendas & Calendriers', N'accessoires-bureau-machines-agendas-calendriers', N'fa-calendar-alt', 1, (SELECT Id FROM Categories WHERE Nom = N'ACCESSOIRES BUREAU & MACHINES' AND ParentId IS NULL)),
  (N'Machines de Bureau', N'accessoires-bureau-machines-machines-de-bureau', N'fa-cogs', 1, (SELECT Id FROM Categories WHERE Nom = N'ACCESSOIRES BUREAU & MACHINES' AND ParentId IS NULL)),
  (N'Reliure & Plastification', N'accessoires-bureau-machines-reliure-plastification', N'fa-id-card', 1, (SELECT Id FROM Categories WHERE Nom = N'ACCESSOIRES BUREAU & MACHINES' AND ParentId IS NULL)),
  (N'Cachets & Dateurs', N'accessoires-bureau-machines-cachets-dateurs', N'fa-stamp', 1, (SELECT Id FROM Categories WHERE Nom = N'ACCESSOIRES BUREAU & MACHINES' AND ParentId IS NULL)),
  (N'Tableaux', N'presentation-communication-tableaux', N'fa-chalkboard-teacher', 1, (SELECT Id FROM Categories WHERE Nom = N'PRÉSENTATION & COMMUNICATION' AND ParentId IS NULL)),
  (N'Accessoires Tableaux', N'presentation-communication-accessoires-tableaux', N'fa-magnet', 1, (SELECT Id FROM Categories WHERE Nom = N'PRÉSENTATION & COMMUNICATION' AND ParentId IS NULL)),
  (N'Vidéoprojection', N'presentation-communication-videoprojection', N'fa-video', 1, (SELECT Id FROM Categories WHERE Nom = N'PRÉSENTATION & COMMUNICATION' AND ParentId IS NULL)),
  (N'Visioconférence', N'presentation-communication-visioconference', N'fa-users', 1, (SELECT Id FROM Categories WHERE Nom = N'PRÉSENTATION & COMMUNICATION' AND ParentId IS NULL)),
  (N'Affichage & Signalétique', N'presentation-communication-affichage-signaletique', N'fa-sign', 1, (SELECT Id FROM Categories WHERE Nom = N'PRÉSENTATION & COMMUNICATION' AND ParentId IS NULL)),
  (N'Ordinateurs & Serveurs', N'informatique-accessoires-ordinateurs-serveurs', N'fa-desktop', 1, (SELECT Id FROM Categories WHERE Nom = N'INFORMATIQUE & ACCESSOIRES' AND ParentId IS NULL)),
  (N'Écrans Moniteurs', N'informatique-accessoires-ecrans-moniteurs', N'fa-tv', 1, (SELECT Id FROM Categories WHERE Nom = N'INFORMATIQUE & ACCESSOIRES' AND ParentId IS NULL)),
  (N'Périphériques', N'informatique-accessoires-peripheriques', N'fa-keyboard', 1, (SELECT Id FROM Categories WHERE Nom = N'INFORMATIQUE & ACCESSOIRES' AND ParentId IS NULL)),
  (N'Stockage', N'informatique-accessoires-stockage', N'fa-hdd', 1, (SELECT Id FROM Categories WHERE Nom = N'INFORMATIQUE & ACCESSOIRES' AND ParentId IS NULL)),
  (N'Réseau', N'informatique-accessoires-reseau', N'fa-network-wired', 1, (SELECT Id FROM Categories WHERE Nom = N'INFORMATIQUE & ACCESSOIRES' AND ParentId IS NULL)),
  (N'Composants PC', N'informatique-accessoires-composants-pc', N'fa-microchip', 1, (SELECT Id FROM Categories WHERE Nom = N'INFORMATIQUE & ACCESSOIRES' AND ParentId IS NULL)),
  (N'Alimentation & Protection', N'informatique-accessoires-alimentation-protection', N'fa-bolt', 1, (SELECT Id FROM Categories WHERE Nom = N'INFORMATIQUE & ACCESSOIRES' AND ParentId IS NULL)),
  (N'Nettoyage & Accessoires Divers', N'informatique-accessoires-nettoyage-accessoires-divers', N'fa-spray-can', 1, (SELECT Id FROM Categories WHERE Nom = N'INFORMATIQUE & ACCESSOIRES' AND ParentId IS NULL)),
  (N'Logiciels', N'informatique-accessoires-logiciels', N'fa-compact-disc', 1, (SELECT Id FROM Categories WHERE Nom = N'INFORMATIQUE & ACCESSOIRES' AND ParentId IS NULL)),
  (N'Imprimantes', N'imprimantes-consommables-imprimantes', N'fa-print', 1, (SELECT Id FROM Categories WHERE Nom = N'IMPRIMANTES & CONSOMMABLES' AND ParentId IS NULL)),
  (N'Photocopieurs', N'imprimantes-consommables-photocopieurs', N'fa-copy', 1, (SELECT Id FROM Categories WHERE Nom = N'IMPRIMANTES & CONSOMMABLES' AND ParentId IS NULL)),
  (N'Cartouches Jet d''Encre', N'imprimantes-consommables-cartouches-jet-d-encre', N'fa-tint', 1, (SELECT Id FROM Categories WHERE Nom = N'IMPRIMANTES & CONSOMMABLES' AND ParentId IS NULL)),
  (N'Toners Laser — Originaux', N'imprimantes-consommables-toners-laser-originaux', N'fa-fill-drip', 1, (SELECT Id FROM Categories WHERE Nom = N'IMPRIMANTES & CONSOMMABLES' AND ParentId IS NULL)),
  (N'Toners Compatibles', N'imprimantes-consommables-toners-compatibles', N'fa-recycle', 1, (SELECT Id FROM Categories WHERE Nom = N'IMPRIMANTES & CONSOMMABLES' AND ParentId IS NULL)),
  (N'Autres Consommables', N'imprimantes-consommables-autres-consommables', N'fa-ellipsis-h', 1, (SELECT Id FROM Categories WHERE Nom = N'IMPRIMANTES & CONSOMMABLES' AND ParentId IS NULL)),
  (N'Bureaux', N'mobilier-de-bureau-bureaux', N'fa-couch', 1, (SELECT Id FROM Categories WHERE Nom = N'MOBILIER DE BUREAU' AND ParentId IS NULL)),
  (N'Sièges & Fauteuils', N'mobilier-de-bureau-sieges-fauteuils', N'fa-chair', 1, (SELECT Id FROM Categories WHERE Nom = N'MOBILIER DE BUREAU' AND ParentId IS NULL)),
  (N'Meubles de Rangement', N'mobilier-de-bureau-meubles-de-rangement', N'fa-warehouse', 1, (SELECT Id FROM Categories WHERE Nom = N'MOBILIER DE BUREAU' AND ParentId IS NULL)),
  (N'Mobilier d''Accueil', N'mobilier-de-bureau-mobilier-d-accueil', N'fa-concierge-bell', 1, (SELECT Id FROM Categories WHERE Nom = N'MOBILIER DE BUREAU' AND ParentId IS NULL)),
  (N'Accessoires Aménagement', N'mobilier-de-bureau-accessoires-amenagement', N'fa-lightbulb', 1, (SELECT Id FROM Categories WHERE Nom = N'MOBILIER DE BUREAU' AND ParentId IS NULL)),
  (N'Sacs & Trousses', N'scolaire-para-scolaire-sacs-trousses', N'fa-school', 1, (SELECT Id FROM Categories WHERE Nom = N'SCOLAIRE & PARA-SCOLAIRE' AND ParentId IS NULL)),
  (N'Cahiers & Blocs', N'scolaire-para-scolaire-cahiers-blocs', N'fa-book', 1, (SELECT Id FROM Categories WHERE Nom = N'SCOLAIRE & PARA-SCOLAIRE' AND ParentId IS NULL)),
  (N'Coloriage & Art', N'scolaire-para-scolaire-coloriage-art', N'fa-paint-brush', 1, (SELECT Id FROM Categories WHERE Nom = N'SCOLAIRE & PARA-SCOLAIRE' AND ParentId IS NULL)),
  (N'Éducatif & Loisirs', N'scolaire-para-scolaire-educatif-loisirs', N'fa-puzzle-piece', 1, (SELECT Id FROM Categories WHERE Nom = N'SCOLAIRE & PARA-SCOLAIRE' AND ParentId IS NULL)),
  (N'Hygiène & Sanitaires', N'services-generaux-hygiene-sanitaires', N'fa-pump-soap', 1, (SELECT Id FROM Categories WHERE Nom = N'SERVICES GÉNÉRAUX' AND ParentId IS NULL)),
  (N'Entretien & Nettoyage', N'services-generaux-entretien-nettoyage', N'fa-broom', 1, (SELECT Id FROM Categories WHERE Nom = N'SERVICES GÉNÉRAUX' AND ParentId IS NULL)),
  (N'Sécurité des Biens & Locaux', N'services-generaux-securite-des-biens-locaux', N'fa-shield-alt', 1, (SELECT Id FROM Categories WHERE Nom = N'SERVICES GÉNÉRAUX' AND ParentId IS NULL)),
  (N'Équipements de Protection Individuelle (EPI)', N'services-generaux-equipements-de-protection-individuelle-epi', N'fa-hard-hat', 1, (SELECT Id FROM Categories WHERE Nom = N'SERVICES GÉNÉRAUX' AND ParentId IS NULL)),
  (N'Petit Électro & Électricité', N'services-generaux-petit-electro-electricite', N'fa-plug', 1, (SELECT Id FROM Categories WHERE Nom = N'SERVICES GÉNÉRAUX' AND ParentId IS NULL)),
  (N'Alimentation & Réception', N'services-generaux-alimentation-reception', N'fa-utensils', 1, (SELECT Id FROM Categories WHERE Nom = N'SERVICES GÉNÉRAUX' AND ParentId IS NULL)),
  (N'Emballage & Manutention', N'services-generaux-emballage-manutention', N'fa-box', 1, (SELECT Id FROM Categories WHERE Nom = N'SERVICES GÉNÉRAUX' AND ParentId IS NULL)),
  (N'Smartphones', N'mobile-telephonie-smartphones', N'fa-mobile', 1, (SELECT Id FROM Categories WHERE Nom = N'MOBILE & TÉLÉPHONIE' AND ParentId IS NULL)),
  (N'Tablettes', N'mobile-telephonie-tablettes', N'fa-tablet-alt', 1, (SELECT Id FROM Categories WHERE Nom = N'MOBILE & TÉLÉPHONIE' AND ParentId IS NULL)),
  (N'Téléphonie Bureau', N'mobile-telephonie-telephonie-bureau', N'fa-phone-office', 1, (SELECT Id FROM Categories WHERE Nom = N'MOBILE & TÉLÉPHONIE' AND ParentId IS NULL)),
  (N'Accessoires Mobile', N'mobile-telephonie-accessoires-mobile', N'fa-battery-full', 1, (SELECT Id FROM Categories WHERE Nom = N'MOBILE & TÉLÉPHONIE' AND ParentId IS NULL)),
  (N'Photo', N'photo-audio-video-photo', N'fa-camera-retro', 1, (SELECT Id FROM Categories WHERE Nom = N'PHOTO, AUDIO & VIDÉO' AND ParentId IS NULL)),
  (N'Vidéo', N'photo-audio-video-video', N'fa-video', 1, (SELECT Id FROM Categories WHERE Nom = N'PHOTO, AUDIO & VIDÉO' AND ParentId IS NULL)),
  (N'Audio', N'photo-audio-video-audio', N'fa-volume-up', 1, (SELECT Id FROM Categories WHERE Nom = N'PHOTO, AUDIO & VIDÉO' AND ParentId IS NULL)),
  (N'Écrans & Affichage', N'photo-audio-video-ecrans-affichage', N'fa-tv', 1, (SELECT Id FROM Categories WHERE Nom = N'PHOTO, AUDIO & VIDÉO' AND ParentId IS NULL)),
  (N'Supports & Accessoires', N'photo-audio-video-supports-accessoires', N'fa-compact-disc', 1, (SELECT Id FROM Categories WHERE Nom = N'PHOTO, AUDIO & VIDÉO' AND ParentId IS NULL)),
  (N'Coffrets & Cadeaux Bureau', N'cadeaux-promotionnel-coffrets-cadeaux-bureau', N'fa-box-open', 1, (SELECT Id FROM Categories WHERE Nom = N'CADEAUX & PROMOTIONNEL' AND ParentId IS NULL)),
  (N'Articles Promotionnels', N'cadeaux-promotionnel-articles-promotionnels', N'fa-bullhorn', 1, (SELECT Id FROM Categories WHERE Nom = N'CADEAUX & PROMOTIONNEL' AND ParentId IS NULL)),
  (N'Impression Personnalisée', N'cadeaux-promotionnel-impression-personnalisee', N'fa-stamp', 1, (SELECT Id FROM Categories WHERE Nom = N'CADEAUX & PROMOTIONNEL' AND ParentId IS NULL)),
  (N'Emballage Cadeaux', N'cadeaux-promotionnel-emballage-cadeaux', N'fa-ribbon', 1, (SELECT Id FROM Categories WHERE Nom = N'CADEAUX & PROMOTIONNEL' AND ParentId IS NULL)),
  (N'Jeux & Divertissement', N'cadeaux-promotionnel-jeux-divertissement', N'fa-dice', 1, (SELECT Id FROM Categories WHERE Nom = N'CADEAUX & PROMOTIONNEL' AND ParentId IS NULL)),
  (N'Déstockage Fournitures Bureau', N'promotions-bonnes-affaires-destockage-fournitures-bureau', N'fa-percentage', 1, (SELECT Id FROM Categories WHERE Nom = N'PROMOTIONS & BONNES AFFAIRES' AND ParentId IS NULL)),
  (N'Déstockage Informatique', N'promotions-bonnes-affaires-destockage-informatique', N'fa-percentage', 1, (SELECT Id FROM Categories WHERE Nom = N'PROMOTIONS & BONNES AFFAIRES' AND ParentId IS NULL)),
  (N'Déstockage Mobilier', N'promotions-bonnes-affaires-destockage-mobilier', N'fa-percentage', 1, (SELECT Id FROM Categories WHERE Nom = N'PROMOTIONS & BONNES AFFAIRES' AND ParentId IS NULL)),
  (N'Déstockage Services Généraux', N'promotions-bonnes-affaires-destockage-services-generaux', N'fa-percentage', 1, (SELECT Id FROM Categories WHERE Nom = N'PROMOTIONS & BONNES AFFAIRES' AND ParentId IS NULL)),
  (N'Machines de Bureau — Bonnes Affaires', N'promotions-bonnes-affaires-machines-de-bureau-bonnes-affaires', N'fa-percentage', 1, (SELECT Id FROM Categories WHERE Nom = N'PROMOTIONS & BONNES AFFAIRES' AND ParentId IS NULL));

-- ════════ NIVEAU 2 (sous-sous-catégories) ════════
INSERT INTO Categories (Nom, Slug, IconeClass, EstActive, ParentId) VALUES
  (N'Papier A4', N'papiers-blancs-ivoires-papier-a4', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Papiers Blancs & Ivoires' AND c0.Nom = N'PAPETERIE')),
  (N'Papier A3', N'papiers-blancs-ivoires-papier-a3', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Papiers Blancs & Ivoires' AND c0.Nom = N'PAPETERIE')),
  (N'Papier Haut Grammage & Spéciaux', N'papiers-blancs-ivoires-papier-haut-grammage-speciaux', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Papiers Blancs & Ivoires' AND c0.Nom = N'PAPETERIE')),
  (N'Papier Pastel', N'papiers-couleurs-papier-pastel', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Papiers Couleurs' AND c0.Nom = N'PAPETERIE')),
  (N'Papier Fluo', N'papiers-couleurs-papier-fluo', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Papiers Couleurs' AND c0.Nom = N'PAPETERIE')),
  (N'Papier Art Graphique', N'papiers-couleurs-papier-art-graphique', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Papiers Couleurs' AND c0.Nom = N'PAPETERIE')),
  (N'Papiers Photo', N'papiers-speciaux-papiers-photo', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Papiers Spéciaux' AND c0.Nom = N'PAPETERIE')),
  (N'Papier Carbone & NCR', N'papiers-speciaux-papier-carbone-ncr', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Papiers Spéciaux' AND c0.Nom = N'PAPETERIE')),
  (N'Autres Papiers Spéciaux', N'papiers-speciaux-autres-papiers-speciaux', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Papiers Spéciaux' AND c0.Nom = N'PAPETERIE')),
  (N'Étiquettes Adhésives', N'etiquettes-papier-listing-etiquettes-adhesives', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Étiquettes & Papier Listing' AND c0.Nom = N'PAPETERIE')),
  (N'Rouleaux & Listing', N'etiquettes-papier-listing-rouleaux-listing', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Étiquettes & Papier Listing' AND c0.Nom = N'PAPETERIE')),
  (N'Enveloppes', N'courrier-enveloppes-enveloppes', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Courrier & Enveloppes' AND c0.Nom = N'PAPETERIE')),
  (N'Pochettes', N'courrier-enveloppes-pochettes', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Courrier & Enveloppes' AND c0.Nom = N'PAPETERIE')),
  (N'Accessoires Courrier', N'courrier-enveloppes-accessoires-courrier', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Courrier & Enveloppes' AND c0.Nom = N'PAPETERIE')),
  (N'Classeurs à Levier', N'classeurs-classeurs-a-levier', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Classeurs' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Classeurs Polypropylène (PP)', N'classeurs-classeurs-polypropylene-pp', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Classeurs' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Classeurs Scolaires', N'classeurs-classeurs-scolaires', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Classeurs' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Types d''Intercalaires', N'intercalaires-types-d-intercalaires', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Intercalaires' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Boîtes Archive Carton', N'archives-boites-boites-archive-carton', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Archives & Boîtes' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Boîtes Archive Polypropylène', N'archives-boites-boites-archive-polypropylene', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Archives & Boîtes' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Autres Contenants', N'archives-boites-autres-contenants', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Archives & Boîtes' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Trieurs', N'trieur-organisation-trieurs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Trieur & Organisation' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Parapheurs', N'trieur-organisation-parapheurs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Trieur & Organisation' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Divers Organisation', N'trieur-organisation-divers-organisation', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Trieur & Organisation' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Chemises Carton', N'chemises-sous-chemises-chemises-carton', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Chemises & Sous-Chemises' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Chemises Plastique', N'chemises-sous-chemises-chemises-plastique', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Chemises & Sous-Chemises' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Chemises Spéciales', N'chemises-sous-chemises-chemises-speciales', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Chemises & Sous-Chemises' AND c0.Nom = N'CLASSEMENT & ARCHIVAGE')),
  (N'Stylos à Bille', N'stylos-stylos-a-bille', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Stylos' AND c0.Nom = N'ÉCRITURE & CORRECTION')),
  (N'Rollers & Gel', N'stylos-rollers-gel', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Stylos' AND c0.Nom = N'ÉCRITURE & CORRECTION')),
  (N'Autres Stylos', N'stylos-autres-stylos', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Stylos' AND c0.Nom = N'ÉCRITURE & CORRECTION')),
  (N'Crayons à Papier', N'crayons-crayons-a-papier', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Crayons' AND c0.Nom = N'ÉCRITURE & CORRECTION')),
  (N'Marqueurs', N'marqueurs-surligneurs-marqueurs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Marqueurs & Surligneurs' AND c0.Nom = N'ÉCRITURE & CORRECTION')),
  (N'Surligneurs', N'marqueurs-surligneurs-surligneurs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Marqueurs & Surligneurs' AND c0.Nom = N'ÉCRITURE & CORRECTION')),
  (N'Correcteurs', N'correction-correcteurs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Correction' AND c0.Nom = N'ÉCRITURE & CORRECTION')),
  (N'Gommes & Taille-Crayons', N'correction-gommes-taille-crayons', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Correction' AND c0.Nom = N'ÉCRITURE & CORRECTION')),
  (N'Agrafeuses', N'agrafage-agrafeuses', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Agrafage' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Agrafes', N'agrafage-agrafes', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Agrafage' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Ôte-agrafes', N'agrafage-ote-agrafes', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Agrafage' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Perforateurs', N'perforation-perforateurs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Perforation' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Trombones', N'attaches-trombones-trombones', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Attaches & Trombones' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Fasteners & Élastiques', N'attaches-trombones-fasteners-elastiques', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Attaches & Trombones' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Épingles & Punaises', N'attaches-trombones-epingles-punaises', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Attaches & Trombones' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Scotch & Adhésifs', N'adhesifs-colles-scotch-adhesifs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Adhésifs & Colles' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Dévidoirs', N'adhesifs-colles-devidoirs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Adhésifs & Colles' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Colles', N'adhesifs-colles-colles', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Adhésifs & Colles' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Notes Adhésives', N'adhesifs-colles-notes-adhesives', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Adhésifs & Colles' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Ciseaux & Cutters', N'decoupe-mesure-ciseaux-cutters', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Découpe & Mesure' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Règles & Équerres', N'decoupe-mesure-regles-equerres', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Découpe & Mesure' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Divers', N'decoupe-mesure-divers', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Découpe & Mesure' AND c0.Nom = N'PETITE FOURNITURE')),
  (N'Cahiers & Carnets', N'cahiers-blocs-cahiers-carnets', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Cahiers & Blocs' AND c0.Nom = N'ACCESSOIRES BUREAU & MACHINES'));

INSERT INTO Categories (Nom, Slug, IconeClass, EstActive, ParentId) VALUES
  (N'Blocs & Registres', N'cahiers-blocs-blocs-registres', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Cahiers & Blocs' AND c0.Nom = N'ACCESSOIRES BUREAU & MACHINES')),
  (N'Agendas', N'agendas-calendriers-agendas', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Agendas & Calendriers' AND c0.Nom = N'ACCESSOIRES BUREAU & MACHINES')),
  (N'Calendriers & Éphémérides', N'agendas-calendriers-calendriers-ephemerides', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Agendas & Calendriers' AND c0.Nom = N'ACCESSOIRES BUREAU & MACHINES')),
  (N'Calculatrices', N'machines-de-bureau-calculatrices', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Machines de Bureau' AND c0.Nom = N'ACCESSOIRES BUREAU & MACHINES')),
  (N'Destructeurs de Documents', N'machines-de-bureau-destructeurs-de-documents', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Machines de Bureau' AND c0.Nom = N'ACCESSOIRES BUREAU & MACHINES')),
  (N'Relieuses', N'reliure-plastification-relieuses', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Reliure & Plastification' AND c0.Nom = N'ACCESSOIRES BUREAU & MACHINES')),
  (N'Plastifieuses', N'reliure-plastification-plastifieuses', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Reliure & Plastification' AND c0.Nom = N'ACCESSOIRES BUREAU & MACHINES')),
  (N'Massicots', N'reliure-plastification-massicots', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Reliure & Plastification' AND c0.Nom = N'ACCESSOIRES BUREAU & MACHINES')),
  (N'Cachets', N'cachets-dateurs-cachets', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Cachets & Dateurs' AND c0.Nom = N'ACCESSOIRES BUREAU & MACHINES')),
  (N'Dateurs', N'cachets-dateurs-dateurs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Cachets & Dateurs' AND c0.Nom = N'ACCESSOIRES BUREAU & MACHINES')),
  (N'Encres & Tampons', N'cachets-dateurs-encres-tampons', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Cachets & Dateurs' AND c0.Nom = N'ACCESSOIRES BUREAU & MACHINES')),
  (N'Tableaux Blancs', N'tableaux-tableaux-blancs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Tableaux' AND c0.Nom = N'PRÉSENTATION & COMMUNICATION')),
  (N'Tableaux Liège & Vitrine', N'tableaux-tableaux-liege-vitrine', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Tableaux' AND c0.Nom = N'PRÉSENTATION & COMMUNICATION')),
  (N'Tableaux Interactifs', N'tableaux-tableaux-interactifs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Tableaux' AND c0.Nom = N'PRÉSENTATION & COMMUNICATION')),
  (N'Vidéoprojecteurs', N'videoprojection-videoprojecteurs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Vidéoprojection' AND c0.Nom = N'PRÉSENTATION & COMMUNICATION')),
  (N'Écrans de Projection', N'videoprojection-ecrans-de-projection', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Vidéoprojection' AND c0.Nom = N'PRÉSENTATION & COMMUNICATION')),
  (N'Systèmes Visio', N'visioconference-systemes-visio', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Visioconférence' AND c0.Nom = N'PRÉSENTATION & COMMUNICATION')),
  (N'Accessoires Conférence', N'visioconference-accessoires-conference', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Visioconférence' AND c0.Nom = N'PRÉSENTATION & COMMUNICATION')),
  (N'PC Bureau & Portables', N'ordinateurs-serveurs-pc-bureau-portables', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Ordinateurs & Serveurs' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Serveurs', N'ordinateurs-serveurs-serveurs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Ordinateurs & Serveurs' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Boutique Apple', N'ordinateurs-serveurs-boutique-apple', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Ordinateurs & Serveurs' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Types d''Écrans', N'ecrans-moniteurs-types-d-ecrans', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Écrans Moniteurs' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Supports d''Écrans', N'ecrans-moniteurs-supports-d-ecrans', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Écrans Moniteurs' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Saisie & Pointage', N'peripheriques-saisie-pointage', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Périphériques' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Audio & Son', N'peripheriques-audio-son', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Périphériques' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Tablettes & Stylets', N'peripheriques-tablettes-stylets', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Périphériques' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Autres Périphériques', N'peripheriques-autres-peripheriques', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Périphériques' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Disques Internes', N'stockage-disques-internes', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Stockage' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Disques Externes', N'stockage-disques-externes', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Stockage' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Stockage Amovible', N'stockage-stockage-amovible', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Stockage' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Mémoire RAM', N'stockage-memoire-ram', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Stockage' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Routeurs & WiFi', N'reseau-routeurs-wifi', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Réseau' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Câbles & Modules', N'reseau-cables-modules', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Réseau' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Composants', N'composants-pc-composants', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Composants PC' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Onduleurs & Stabilisateurs', N'alimentation-protection-onduleurs-stabilisateurs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Alimentation & Protection' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Nettoyage Informatique', N'nettoyage-accessoires-divers-nettoyage-informatique', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Nettoyage & Accessoires Divers' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Divers', N'nettoyage-accessoires-divers-divers', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Nettoyage & Accessoires Divers' AND c0.Nom = N'INFORMATIQUE & ACCESSOIRES')),
  (N'Jet d''Encre', N'imprimantes-jet-d-encre', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Imprimantes' AND c0.Nom = N'IMPRIMANTES & CONSOMMABLES')),
  (N'Laser', N'imprimantes-laser', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Imprimantes' AND c0.Nom = N'IMPRIMANTES & CONSOMMABLES')),
  (N'Imprimantes Spéciales', N'imprimantes-imprimantes-speciales', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Imprimantes' AND c0.Nom = N'IMPRIMANTES & CONSOMMABLES')),
  (N'Copieurs MFP', N'photocopieurs-copieurs-mfp', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Photocopieurs' AND c0.Nom = N'IMPRIMANTES & CONSOMMABLES')),
  (N'Cartouches Originales', N'cartouches-jet-d-encre-cartouches-originales', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Cartouches Jet d''Encre' AND c0.Nom = N'IMPRIMANTES & CONSOMMABLES')),
  (N'Cartouches Compatibles', N'cartouches-jet-d-encre-cartouches-compatibles', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Cartouches Jet d''Encre' AND c0.Nom = N'IMPRIMANTES & CONSOMMABLES')),
  (N'Toners pour Imprimantes', N'toners-laser-originaux-toners-pour-imprimantes', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Toners Laser — Originaux' AND c0.Nom = N'IMPRIMANTES & CONSOMMABLES')),
  (N'Toners pour Photocopieurs', N'toners-laser-originaux-toners-pour-photocopieurs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Toners Laser — Originaux' AND c0.Nom = N'IMPRIMANTES & CONSOMMABLES')),
  (N'Calculatrices & Caisses', N'autres-consommables-calculatrices-caisses', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Autres Consommables' AND c0.Nom = N'IMPRIMANTES & CONSOMMABLES')),
  (N'Autres', N'autres-consommables-autres', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Autres Consommables' AND c0.Nom = N'IMPRIMANTES & CONSOMMABLES')),
  (N'Bureaux par Type', N'bureaux-bureaux-par-type', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Bureaux' AND c0.Nom = N'MOBILIER DE BUREAU')),
  (N'Tables de Réunion', N'bureaux-tables-de-reunion', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Bureaux' AND c0.Nom = N'MOBILIER DE BUREAU')),
  (N'Autres Tables', N'bureaux-autres-tables', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Bureaux' AND c0.Nom = N'MOBILIER DE BUREAU'));

INSERT INTO Categories (Nom, Slug, IconeClass, EstActive, ParentId) VALUES
  (N'Fauteuils Direction', N'sieges-fauteuils-fauteuils-direction', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Sièges & Fauteuils' AND c0.Nom = N'MOBILIER DE BUREAU')),
  (N'Sièges Opérateurs', N'sieges-fauteuils-sieges-operateurs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Sièges & Fauteuils' AND c0.Nom = N'MOBILIER DE BUREAU')),
  (N'Sièges Ergonomiques', N'sieges-fauteuils-sieges-ergonomiques', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Sièges & Fauteuils' AND c0.Nom = N'MOBILIER DE BUREAU')),
  (N'Autres Sièges', N'sieges-fauteuils-autres-sieges', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Sièges & Fauteuils' AND c0.Nom = N'MOBILIER DE BUREAU')),
  (N'Armoires', N'meubles-de-rangement-armoires', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Meubles de Rangement' AND c0.Nom = N'MOBILIER DE BUREAU')),
  (N'Caissons', N'meubles-de-rangement-caissons', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Meubles de Rangement' AND c0.Nom = N'MOBILIER DE BUREAU')),
  (N'Autres Rangements', N'meubles-de-rangement-autres-rangements', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Meubles de Rangement' AND c0.Nom = N'MOBILIER DE BUREAU')),
  (N'Sacs à Dos', N'sacs-trousses-sacs-a-dos', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Sacs & Trousses' AND c0.Nom = N'SCOLAIRE & PARA-SCOLAIRE')),
  (N'Trousses', N'sacs-trousses-trousses', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Sacs & Trousses' AND c0.Nom = N'SCOLAIRE & PARA-SCOLAIRE')),
  (N'Accessoires Scolaires', N'sacs-trousses-accessoires-scolaires', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Sacs & Trousses' AND c0.Nom = N'SCOLAIRE & PARA-SCOLAIRE')),
  (N'Cahiers Scolaires', N'cahiers-blocs-cahiers-scolaires', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Cahiers & Blocs' AND c0.Nom = N'SCOLAIRE & PARA-SCOLAIRE')),
  (N'Classeurs Scolaires', N'cahiers-blocs-classeurs-scolaires', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Cahiers & Blocs' AND c0.Nom = N'SCOLAIRE & PARA-SCOLAIRE')),
  (N'Crayons & Feutres', N'coloriage-art-crayons-feutres', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Coloriage & Art' AND c0.Nom = N'SCOLAIRE & PARA-SCOLAIRE')),
  (N'Peintures', N'coloriage-art-peintures', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Coloriage & Art' AND c0.Nom = N'SCOLAIRE & PARA-SCOLAIRE')),
  (N'Activités Manuelles', N'educatif-loisirs-activites-manuelles', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Éducatif & Loisirs' AND c0.Nom = N'SCOLAIRE & PARA-SCOLAIRE')),
  (N'Jeux Éducatifs', N'educatif-loisirs-jeux-educatifs', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Éducatif & Loisirs' AND c0.Nom = N'SCOLAIRE & PARA-SCOLAIRE')),
  (N'Hygiène des Mains', N'hygiene-sanitaires-hygiene-des-mains', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Hygiène & Sanitaires' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Papier & Essuie-Mains', N'hygiene-sanitaires-papier-essuie-mains', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Hygiène & Sanitaires' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Autres Hygiène', N'hygiene-sanitaires-autres-hygiene', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Hygiène & Sanitaires' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Machines de Nettoyage', N'entretien-nettoyage-machines-de-nettoyage', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Entretien & Nettoyage' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Nettoyants & Désinfectants', N'entretien-nettoyage-nettoyants-desinfectants', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Entretien & Nettoyage' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Consommables Nettoyage', N'entretien-nettoyage-consommables-nettoyage', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Entretien & Nettoyage' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Contrôle d''Accès', N'securite-des-biens-locaux-controle-d-acces', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Sécurité des Biens & Locaux' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Coffres & Armoires Fortes', N'securite-des-biens-locaux-coffres-armoires-fortes', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Sécurité des Biens & Locaux' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Protection Incendie', N'securite-des-biens-locaux-protection-incendie', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Sécurité des Biens & Locaux' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Vidéosurveillance', N'securite-des-biens-locaux-videosurveillance', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Sécurité des Biens & Locaux' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Divers Sécurité', N'securite-des-biens-locaux-divers-securite', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Sécurité des Biens & Locaux' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Protection du Corps', N'equipements-de-protection-individuelle-epi-protection-du-corps', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Équipements de Protection Individuelle (EPI)' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Vêtements de Travail', N'equipements-de-protection-individuelle-epi-vetements-de-travail', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Équipements de Protection Individuelle (EPI)' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Café & Boissons Chaudes', N'petit-electro-electricite-cafe-boissons-chaudes', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Petit Électro & Électricité' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Froid & Climatisation', N'petit-electro-electricite-froid-climatisation', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Petit Électro & Électricité' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Électricité', N'petit-electro-electricite-electricite', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Petit Électro & Électricité' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Vaisselle & Service', N'alimentation-reception-vaisselle-service', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Alimentation & Réception' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Alimentaire', N'alimentation-reception-alimentaire', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Alimentation & Réception' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Emballage', N'emballage-manutention-emballage', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Emballage & Manutention' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Manutention', N'emballage-manutention-manutention', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Emballage & Manutention' AND c0.Nom = N'SERVICES GÉNÉRAUX')),
  (N'Téléphones & Fax', N'telephonie-bureau-telephones-fax', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Téléphonie Bureau' AND c0.Nom = N'MOBILE & TÉLÉPHONIE')),
  (N'Accessoires Téléphonie', N'telephonie-bureau-accessoires-telephonie', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Téléphonie Bureau' AND c0.Nom = N'MOBILE & TÉLÉPHONIE')),
  (N'Appareils Photo', N'photo-appareils-photo', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Photo' AND c0.Nom = N'PHOTO, AUDIO & VIDÉO')),
  (N'Caméscopes & Surveillance', N'video-camescopes-surveillance', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Vidéo' AND c0.Nom = N'PHOTO, AUDIO & VIDÉO')),
  (N'Enceintes & Son', N'audio-enceintes-son', N'fa-tag', 1, (SELECT c1.Id FROM Categories c1 INNER JOIN Categories c0 ON c1.ParentId = c0.Id WHERE c1.Nom = N'Audio' AND c0.Nom = N'PHOTO, AUDIO & VIDÉO'));

COMMIT TRANSACTION;

-- TOTAL : 15 principales + 82 sous + 141 sous-sous
-- + 1 'À reclasser' qui contient temporairement tes anciens produits
PRINT N'Catégories réinitialisées avec succès.';